//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTE()
        {
            this.DOCS_CC = new HashSet<DOCS_CC>();
            this.FACTURA = new HashSet<FACTURA>();
            this.RECIBO = new HashSet<RECIBO>();
        }
    
        public int CLIENTE_ID { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
        public Nullable<int> CODIGO_CLTE { get; set; }
        public string NOMBRE_CLTE { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string CONTACTO { get; set; }
        public string E_MAIL { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<bool> CLTE_ACTIVO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<decimal> MONTO_ULT_TRAN { get; set; }
        public Nullable<System.DateTime> FECHA_ULT_TRAN { get; set; }
        public Nullable<decimal> DESC_ULT_TRAN { get; set; }
        public string NIT { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCS_CC> DOCS_CC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIBO> RECIBO { get; set; }
    }
}
