//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOCS_CC
    {
        public int DOC_ID { get; set; }
        public Nullable<int> TIPO_DOC_ID { get; set; }
        public Nullable<int> FORMA_PAGO_ID { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
        public Nullable<int> CLIENTE_ID { get; set; }
        public Nullable<int> NRO_DOC { get; set; }
        public Nullable<System.DateTime> FECHA_EMISION { get; set; }
        public string DESC_DOC { get; set; }
        public Nullable<decimal> MONTO_DOC { get; set; }
        public Nullable<decimal> MONTO_PARCIAL { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public Nullable<int> NRO_PAGOS { get; set; }
        public Nullable<decimal> BALANCE { get; set; }
        public Nullable<int> NRO_DOC_PAGADO { get; set; }
        public Nullable<int> ID_PAGADO { get; set; }
        public Nullable<int> ID_ORIGEN { get; set; }
        public Nullable<System.DateTime> FECHA_HORA { get; set; }
        public Nullable<int> ID_BASE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
