//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURA_DETALLE
    {
        public int DETALLE_ID { get; set; }
        public Nullable<int> FACTURA_ID { get; set; }
        public Nullable<int> PRODUCTO_ID { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO_FACTURA { get; set; }
        public Nullable<bool> ANULADA { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
