//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIBO
    {
        public int RECIBO_ID { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
        public Nullable<int> CLIENTE_ID { get; set; }
        public Nullable<int> FORMA_PAGO_ID { get; set; }
        public Nullable<int> NRO_RECIBO { get; set; }
        public Nullable<System.DateTime> FECHA_EMISION { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<bool> ANULADO { get; set; }
        public string CAUSA_ANULADO { get; set; }
        public string DESCRIPCION { get; set; }
        public string NRO_DOC_PAGO { get; set; }
        public Nullable<int> NRO_FACTURA { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
