//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECIBO_DETALLE
    {
        public int RECIBO_DETALLE_ID { get; set; }
        public Nullable<int> RECIBO_ID { get; set; }
        public Nullable<int> FACTURA_ID { get; set; }
        public Nullable<int> NOTA_CARGO_ID { get; set; }
        public string DESCRIPCION { get; set; }
        [DisplayFormat(DataFormatString = "{0:N}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<int> TIPO_DOC_ID { get; set; }
        public Nullable<int> DOC_NRO { get; set; }
    
        public virtual FACTURA FACTURA { get; set; }
        public virtual NOTA_CARGO NOTA_CARGO { get; set; }
        public virtual RECIBO RECIBO { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
    }
}
