//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inspinia_MVC5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERIE_DOCUMENTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SERIE_DOCUMENTO()
        {
            this.FACTURA = new HashSet<FACTURA>();
        }
    
        public int SERIE_DOC_ID { get; set; }
        public Nullable<int> TIPO_DOC_ID { get; set; }
        public Nullable<int> USUARIO_ID { get; set; }
        public string SERIE { get; set; }
        public string RESOLUCION { get; set; }
        public Nullable<decimal> DESDE { get; set; }
        public Nullable<decimal> HASTA { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION { get; set; }
        public Nullable<System.DateTime> FECHA_VIGENTE { get; set; }
        public Nullable<System.DateTime> FECHA_RESOLUCION { get; set; }
        public Nullable<bool> SERIE_ACTIVO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURA> FACTURA { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
